--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/Wilderness
branches:
- master
- api4
- pm5
projects:
  Wilderness:
    path: ""
    libs:
      - src: SOF3/await-generator/await-generator
        version: ^3.4.2
...
