name: Wilderness
main: muqsit\wilderness\Loader
api: 4.0.0
version: 1.1.0

commands:
  wilderness:
    aliases: ["wild"]
    permission: wilderness.command

permissions:
  wilderness.command:
    default: op