name: Wilderness
main: muqsit\wilderness\Loader
api: 3.14.0
version: 1.1.0

commands:
  wilderness:
    aliases: ["wild"]
    permission: wilderness.command

permissions:
  wilderness:
    default: false
    childrern:
      wilderness.command:
        default: op